#!/bin/bash

# Catch Ctrl+c to automatically run final build
trap signal_handler INT 
signal_handler() 
{ 
    dev/script/assets_build
} 

# Install dependencies if necessary
dev/script/assets_install

# Run webpack compilation in watch mode
echo "Launching assets building in watch mode..."
dev/bin/npm run watch
