#!/usr/bin/env bash

PRINT_HELP() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options :"
    echo "  -h, --help      Display this help"
    echo "  -f, --folder    Destination folder in dev folder"
}

while [[ $# -gt 0 ]] 
do
    key="$1"
    value="$2"
    case $key in
        -h|--help)
            PRINT_HELP
            exit 0
        ;;
        -f|--folder)
            FOLDER=${value:-"dist"}
            shift # past argument
            shift # past value
        ;;
        ?)
        echo "Unknown option : $1"
            PRINT_HELP
            exit 1
        ;;
    esac
done

FOLDER=${FOLDER:-"dist"}

# Generating a dump inside database container
echo "Generating dump..."
dev/bin/mysqldump "--no-tablespaces > /tmp/dump.sql"
echo "Dump generated!"

# Replacing current url by url placeholder
echo "Updating url in dump..."
APP_URL=$(docker-compose exec app bash -c 'echo $VIRTUAL_HOST')
docker-compose exec app sed -i s/$APP_URL/__VIRTUAL_HOST__/g /tmp/dump.sql
echo "Url updated!"

# Compressing dump
echo "Compressing dump..."
dev/bin/tar --zstd -cf /tmp/dump.sql.tar.zst /tmp/dump.sql
docker-compose exec app rm /tmp/dump.sql
echo "Dump compressed!"

# Copy dump from database to the host
echo "Copying dump from container to host..."
mkdir -p ./dev/$FOLDER
docker-compose cp app:/tmp/dump.sql.tar.zst ./dev/$FOLDER/dump.sql.tar.zst
docker-compose exec app rm /tmp/dump.sql.tar.zst
echo "Dump copied!"
